nohup nextflow run /czlab/xuwen/scripts/PreP-ubam2bam-BWA-variant-GATK4/processing-for-variant-discovery-gatk4MT2T.nf \
    -profile hpc_slurm \
    -c /czlab/xuwen/results/NA12878/300X/scripts/nextflowT2T.config \
    -work-dir /czlab/xuwen/results/NA12878/300X/workspaces/PreP-ubam2bam-BWA-variant-GATK4/T2T/work \
    --outdir /czlab/xuwen/results/NA12878/300X/T2ToutDir/ \
    --unmapped_bams_list /czlab/xuwen/results/NA12878/300X/unmapped_bams/unmapped_bams.tsv \
    --projectId NA12878 \
    -with-report processing-for-variant-discovery-gatk4.html \
    -with-dag processing-for-variant-discovery-gatk4.flowchart.png \
    -with-trace trace.txt \
    -N sherwinmabos@gmail.com \
    -bg \
    -resume &
